### ISSUE TITLE
Animations that use images don't work.

### ISSUE THREAD

**Issue by XBLDev** [react-community/lottie-react-native#228]
I'm currently using easy-lottie-react-native: https://www.npmjs.com/package/easy-lottie-react-native, and for some reason all the animations that use images don't work. 

I put the "animations" folder in the "node_modules" and I put the "images" folder which contains all the images needed in the "animations" folder, and the JSON animation files are all in the "animations" folder.

Maybe I'm putting the folders in the wrong places? Or is there anything else that could be the cause?

**Comment by romitmewada** [comment]
did you fix your issue?

**Comment by XBLDev** [comment]
hi @romitmewada no I don't think i solved them, they still don't work on React Native

**Comment by romitmewada** [comment]
I figure out this issue for android. created assets folder in Android. 

images path is 'App/android/app/src/main/assets/lottie/image/img.png'

`<LottieAnimation source={require('../animation/data.json')} style={styles.animation} imageAssetsFolder='lottie/image'>.
`
Still trying to fix for iOS.

**Comment by cth0mas** [comment]
Having this issue as well...  Pretty much sucks as I have like 20 animations that ALL have img files to put in the application I'm building.

**Comment by XBLDev** [comment]
@romitmewada Hey thanks man I'll try it, and get back to you if it works for me :-)

**Comment by XBLDev** [comment]
@cth0mas Hey man see if @romitmewada solution works for you?

**Comment by cth0mas** [comment]
I did get this working.  

imageAssetsFolder is required for Android, and it is relative to the final bundle.  For instance I have all my animation images in my android project resources (resources/lottie/images) so my imageAssetsFolder={"lottie/images"}.  In XCode you must add each image required in your animations by right clicking and selected add file on the resources folder in your project.  Aside from following the github setup instructions that is all that was required.

**Comment by stahlmanDesign** [comment]
I got this working for the web using React and create-react-app. I had to put the images folder generated by the Render action in AE into the /public folder of the React project (at the same level as /src)

**Comment by fxyong** [comment]
I managed to get it working in iOS..
However, in Android.. the image simply just doesnt shows. 
I've already added the imageAssetsFolder='lottie/image'

any help is much appreciated.

**Comment by witalobenicio** [comment]
@fxyong how you made work in ios?

**Comment by JayKurniawan** [comment]
the image is not showing up.. where should I put the image ?
