### ISSUE TITLE
Allow loop prop to take a number

### ISSUE THREAD

**Issue by mjsisley** [react-community/lottie-react-native#231]
Thoughts on allowing the loop prop to take a number as an option (instead of only boolean)?

For cases where you want the animation to loop some amount of times less than infinity.

**Comment by emilioicai** [comment]
This feature should be implemented in the native modules first. @mjsisley if you are still interested in having it you can request it there: https://github.com/airbnb/lottie-android and https://github.com/airbnb/lottie-ios
