### ISSUE TITLE
Warning: Failed prop type: Cannot convert undefined or null to object     in LottieAnimation (at createAnimatedComponent.js:134)

### ISSUE THREAD

**Issue by biqiaoran629** [react-community/lottie-react-native#243]
Using code from get started:
...
    componentDidMount() {
        this.animation.play();
    }
...
render() {
return (
                    <View>
                        <LottieView
                            ref={animation => {
                                this.animation = animation;
                            }}
                            source={require('../../images/servishero_loading.json')}
                        />
                    </View>
);
}

Versions:
    "react-native": "0.49.5",
    "lottie-react-native": "2.2.7",

**Comment by pelim** [comment]
same error by me

**Comment by jsknight** [comment]
I have this same issue also.

**Comment by peteroid** [comment]
A hacky fix is to add an empty style attribute as `style={{ }}` in your `LottleView`.

**Comment by gpeal** [comment]
Can you reopen this if it's still an issue with 2.3.0?

**Comment by abdullah-sr** [comment]
this is still an issue with 2.5.6

**Comment by emilioicai** [comment]
I just submitted a fix for this. Should be available on master and in 2.5.10
