### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by pplanel** [react-community/lottie-react-native#252]
Trying hard to get running with this lib. But no deal...

**Comment by gran33** [comment]
Same here, `2.3.1` doesn't have anything relevant in `/lib` folder.
:/

**Comment by calvinmikael** [comment]
I'm unaffiliated with this project.

In 2.3.1 the files are in the src folder instead of lib.

```
include ':lottie-react-native'
project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')
```

When adding the LottiePackage
```
@Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
            new LottiePackage()
```

You must also import Lottie above
```
import com.airbnb.android.react.lottie.LottiePackage;
```

**Comment by gran33** [comment]
I did this but seems like weird that such big project like this, and his master is broken :(

**Comment by calvinmikael** [comment]
Feel free to suggest/push for moving this project to the react community repository. Recently other unmaintained projects by AirBnB such as react-native-maps have been moved there as it becomes apparent their priorities are (rightfully) elsewhere.

**Comment by kyle-ssg** [comment]
+1 - this project is a pain to setup

**Comment by sabbyt54** [comment]
+1

**Comment by gpeal** [comment]
@calvinmikael I would support this move as per #284. I'll investigate potentially doing this.

**Comment by padupuy** [comment]
@pplanel @gran33 @kyle-ssg @sabbyt54 @gpeal check installation instructions for iOS https://github.com/airbnb/lottie-react-native/issues/177#issuecomment-374908415

**Comment by emilioicai** [comment]
Now this lib is moved to react-community
