### ISSUE TITLE
in ios  error  @import <lottie/lottie.h> is not find

### ISSUE THREAD

**Issue by 594904020** [react-community/lottie-react-native#259]

**Comment by kytwb** [comment]
Fresh install or after an upgrade?

**Comment by tarekgabarin** [comment]
@kytwb I got it after doing a fresh `npm install` after forking production code

**Comment by kytwb** [comment]
@tarekgabarin did you add `Lottie.framework` to **Embedded Libraries**? Check the closed issues, it has been mentioned coupe of times.

**Comment by swdenglian** [comment]
#177
