### ISSUE TITLE
Size of lottie animations don't fill up the container

### ISSUE THREAD

**Issue by VicFrolov** [react-community/lottie-react-native#261]
It seems the animations from .json require excessive padding/margins to be viewable:

![screen shot 2018-01-01 at 6 17 27 pm](https://user-images.githubusercontent.com/8305711/34472891-221217d4-ef20-11e7-8a71-ca4c0431117f.png)

```
      import Animation from 'lottie-react-native';
      // a bunch of other code
      <Animation
        style={{
          backgroundColor: 'red',
          width: 100,
          height: 100,
          resizeMode: 'contain',
        }}
        source={lottieLoader}
        progress={this.state.progress}
      />
```

This doesn't show up in the container, however if I add excessive padding it does:

![screen shot 2018-01-01 at 6 19 04 pm](https://user-images.githubusercontent.com/8305711/34472904-46bc9640-ef20-11e7-8981-a08136ffc2f8.png)

```
      import Animation from 'lottie-react-native';
      // a bunch of other code

      <Animation
        style={{
          backgroundColor: 'red',
          width: 100,
          height: 100,
          paddingTop: 100,
          paddingRight: 300,
          resizeMode: 'contain',
        }}
        source={lottieLoader}
        progress={this.state.progress}
      />
```

Using the following share animation: https://www.lottiefiles.com/search?q=share

**Comment by redpandatronicsuk** [comment]
Googling for a similar error brought me here. I also saw my animation being displayed outside the container. Wrapping the <Animation> in a <View> fixed it for me in the end.
e.g:
```
<View>
  <Animation
        style={{
          backgroundColor: 'red',
          width: 100,
          height: 100
        }}
        source={lottieLoader}
        progress={this.state.progress}
      />
</View>
```

**Comment by VicFrolov** [comment]
I can't seem to get the animation itself to fit in it's parent view edge to edge, which makes it hard to position them side by side:

      <TouchableOpacity
        onPress={this.animate}
        underlayColor="transparent"
        disabled={this.state.midAnimation}
        style={{ height: 100, width: 100 }}
      >
        <Animation
          style={{
            backgroundColor: 'red',
            flex: 1,
            height: 100,
            width: 100,
            padding: 0,
            margin: 0,
          }}
          source={LottieAnimation}
          progress={this.state.progress}
        />
      </TouchableOpacity>

the red background is TouchableOpacity which is 100x100, but the ticket itself has way too much padding on the inside, and makes it basically impossible to line these up as a list.

<img width="82" alt="screen shot 2018-01-12 at 1 48 42 pm" src="https://user-images.githubusercontent.com/8305711/34897041-077de540-f7a1-11e7-99a9-a868a8efe199.png">

**Comment by buba447** [comment]
Try setting the animations contentMode to .scaleAspectFit or .scaleAspectFill

**Comment by VicFrolov** [comment]
Tried both, no luck :/

**Comment by buba447** [comment]
The padding itself comes from the JSON. Its baked into the animation's bounds. Whoever made the animation put a ton of padding around the composition :( 
<img width="453" alt="screen shot 2018-01-12 at 2 48 10 pm" src="https://user-images.githubusercontent.com/1163980/34898384-ac7995a2-f7a7-11e7-8e54-43788d783dec.png">

**Comment by VicFrolov** [comment]
aghhh I thought that was the issue but was hoping there was a way to get rid of the empty padding, that's crazy how on earth would we then scale it to zoom and properly position itself amongst our other icons/textfields.

**Comment by monotv** [comment]
Is there an editor we can use to change basic things like width/height? The Lottie editor only changes colors. I wanted to fiddle around with animations from lottiefiles.com and a lot of them have massive paddings. I don't own AE or plan on buying it just to edit some lottie animations.

**Comment by galechus** [comment]
@monotv, try Keyshape

**Comment by Winglonelion** [comment]
We met this issues in all of our Lottie components. So, by a stupid way, we scale it up by 1.2 (in almost times)

**Comment by arjunpola** [comment]
I have the same issue on Android. I tried setting the scale to 2.x but it scales up the whole view ( which includes padding) and does not solve the problem. Does anyone know if there is a way to hand edit the json to fix the padding?

**Comment by Winglonelion** [comment]
<Lottie
...
resizeMode="cover"
/>

@arjunpola  Above is solution for your

**Comment by WrathChaos** [comment]
Sorry for the resurrect the issue but just for an update. On my project, I just need a perfect square button touchable with Lottie so resizeMode="center" works for me.  Something like that:

```js
<TouchableOpacity
      style={{ height: 70, aspectRatio: 1, backgroundColor: "red" }}
>
      <LottieView
        resizeMode="center"
        progress={progress}
        source={require("your-lottie.json")}
      />
</TouchableOpacity>
```


![Simulator Screen Shot - iPhone X - 2019-10-11 at 00 08 14](https://user-images.githubusercontent.com/6813862/66606660-3ad59b80-ebbb-11e9-8934-e59681b9d064.png)

**Comment by WrathChaos** [comment]
> ```
> <Lottie
> ...
> resizeMode="cover"
> />
> ```
> 
> @arjunpola Above is solution for you

Hey again @Winglonelion,
Unfortunately, I could not resolve my problem to use lottie animations on RN. Simply, resizeMode="cover" does not solve the problem for me. It does not cover the whole padding it just too small. Can you help me to solve it? @Winglonelion 
![Screenshot 2019-10-12 at 12 13 13](https://user-images.githubusercontent.com/6813862/66698794-b3d31100-ece9-11e9-859b-3d535a960029.png)

**Comment by ShaharyarMaroof** [comment]
@WrathChaos I got the animation to get full width by setting the resizeMode to cover as you suggested. Also I have removed it from any wrapping Views.

**Comment by AnandKuhar1100** [comment]
Use aspectRatio in Lottie styles as aspectRatio: deviceWidth/deviceHeight
