### ISSUE TITLE
[Help Wanted] React Native maintainer

### ISSUE THREAD

**Issue by gpeal** [react-community/lottie-react-native#284]
I have primarily focused my efforts on the Android version of Lottie and don't actively use the React Native one for any of my projects. However, Lottie React Native is an important project and is actively used by many people. I don't want to do the community a disservice but I don't have the time to effectively manage this project and make sure that it stays healthy.

I am open to providing support to anybody who would like to help out and maintain Lottie React Native.

**Comment by cdlewis** [comment]
Yeah totally! We use this a lot internally so if there are ways I can help out I'd be totally down. Are there some specific tasks you have mind?

**Comment by gpeal** [comment]
@cdlewis Awesome! 
Some things that come to mind are:
1) Helping triage/handle issues
2) Reviewing PRs
3) Updating to the test version of lottie (2.5.0 is now out on both platforms)
4) Adding bridges for new features

**Comment by gpeal** [comment]
@cdlewis Can you email me at my first name dot last name at airbnb.com if you're interested? I can help you ramp up.

**Comment by Minishlink** [comment]
Hey @gpeal, I'm also interested since we use this library on several projects at [BAM](https://github.com/bamlab). I'm sending you an email :)

**Comment by getElementByClass** [comment]
When I use this plug-in, the image will not be rendered, although I have introduced these files, what is the problem?This is my code structure.
```
<LottieView 
        ref={Animation => {
          this.Animation = Animation
        }}
        // progress={this.state.progress}
        source={require('../../data.json')} 
        autoSize={true}
        imageAssetsFolder="images"
        speed={1}
        autoPlay={true}
        loop={true}
        />
```
