### ISSUE TITLE
Installation Failure

### ISSUE THREAD

**Issue by alexsmartens** [react-community/lottie-react-native#286]
Hi @gpeal, 
I'm impressed with lottie animations that I've seen so far. I'd like to add lottie-react-native to my project. However, I'm having troubles with installing it. Would you please help me with this problem

I'm having the errors while compiling my project with lottie-react-native. I followed [the documentation installation steps](http://airbnb.io/lottie/react-native/react-native.html). I tested both installation options automated and manual. Here is my initial error:

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > Project :app declares a dependency from configuration 'compile' to configuration 'default' which is not declared in the descriptor for project :lottie-react-native.
```

I went over multiple issues but this does not seem to help.  I followed the steps proposed in #203 by @gianpaj and @spearmootz. Here is what I got:
```
:lottie-react-native:generateReleaseBuildConfig FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lottie-react-native:generateReleaseBuildConfig'.
> java.io.IOException: Could not delete path 'D:\myPATH\myApp\node_modules\lottie-react-native\src\android\build\generated\source\buildConfig\release\com\airbnb'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

I also went over #236 and followed the steps proposed by @oximer. Here's what I got:
```
Error: Cannot create directory D:\myPATH\myApp\node_modules\lottie-react-native\src\android\build\intermediates\incremental\mergeReleaseResources\merged.dir\values
:lottie:mergeReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lottie:mergeReleaseResources'.
> Error: Cannot create directory D:\myPATH\myApp\node_modules\lottie-react-native\src\android\build\intermediates\incremental\mergeReleaseResources\merged.dir\values
```

The other issues I found relevant to this problem are #158, #112, #213, #241 and #246.

My environment:
React Native version: RN 0.51.0
Platform: Android 6.0 device (Moto G 2nd Generation)

What do you think?

**Comment by s-shiva1995** [comment]
@alexsmartens I was also facing the same issue 
`Execution failed for task ':lottie-react-native:generateReleaseBuildConfig'.`
I simply created the directories it was not able to create while building in the specified path and then the app was able to build successfully.

Hope it helps.

**Comment by alexsmartens** [comment]
@s-shiva1995 can you explain please? Maybe paste a code snippet

**Comment by AnandanRajkumar** [comment]
I have deleted folder inside the "\node_modules\lottie-react-native\src\android\build\" build folder and run react-native run-android commend it's works for me
