### ISSUE TITLE
android crashed when run up the app

### ISSUE THREAD

**Issue by pohsiu** [react-community/lottie-react-native#288]
`"lottie-react-native": "^2.3.2",
"react": "16.2.0",
    "react-native": "0.53.3",`

every installation and linking is worked and no failure
BUILD SUCCESSFUL

but when the app is going to run,
it just crashed with no reason
the difference is only I use LottieView and not used....

How to fix it?
Is android version stable?

**Comment by pohsiu** [comment]
any solution?????

**Comment by pohsiu** [comment]
still have same issue @ 2.5.0

**Comment by MohanadeviK** [comment]
@pohsiu any solution for this. I have same issue.

**Comment by emilkarl** [comment]
I've got the same issue using some Lottie files. App crashes on start and I get no more errors :/

<img width="700" alt="genymotion for personal use - google nexus 6 - 6 1440x2560 560dpi - 192 168 57 101 2018-07-26 00-28-50" src="https://user-images.githubusercontent.com/10711/43231078-16c6eb1a-906b-11e8-992e-931debeebc76.png">

**Comment by emilioicai** [comment]
I just published 2.5.6 containing some build fixes. Can you try with that one and let me know if the issue is still there?

**Comment by emilkarl** [comment]
@emilioicai still having the same issue. Works good in iOS but fails in Android and it seems to be Lottie file specific :(

**Comment by emilkarl** [comment]
Seems to be an issue with what version it is. Lottie fields with `"v": "5.1.1"` works but not the ones with `"5.0.0"`

**Comment by emilioicai** [comment]
yes, it looks like an issue with the version of your lottie files.
