### ISSUE TITLE
Since 2.3.0 Android build is broken

### ISSUE THREAD

**Issue by ifero** [react-community/lottie-react-native#295]
Hello,
I am working on a cross-platform app using:
* react-native@0.51.0
At the beginning I've started Lottie integration with version 2.3.2
On iOS it worked ok.
Then I tried to build the project on Android and obviously something went wrong:
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not resolve project :lottie-react-native.
     Required by:
         project :app
      > Project :app declares a dependency from configuration '_debugApkCopy' to configuration 'default' which is not declared in the descriptor for project :lottie-react-native.
````
I've looked everywhere with no solution. Then I tried to rollback to older versions: 2.3.1/0 are broken too.
Passed to 2.2.7 and it builds. Unfortunately at the moment I decide to show an animation then it does not appear and get a Warning of type:
`Failed prop type: undefined is not an object(evaluating 'Object.keys(flattened)') in LottieAnimation ...`

any idea?

**Comment by itchingpixels** [comment]
We had the same problem, but managed to resolve it by changing the path in settings.gradle:
`project(':lottie-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/lottie-react-native/src/android')` to `src` (previously `lib`)
