### ISSUE TITLE
Problem in Android device after removing/ uninstalling Lottie -  undefined is not an object (evaluating reactNative.UIManager.LottieAnimationView.Commands)

### ISSUE THREAD

**Issue by Luckygirlllll** [react-community/lottie-react-native#303]
I have deleted Lottie from the project: 

```
react-native unlink lottie-react-native
react-native unlink lottie-ios
react-native uninstall lottie-react-native 
react-native uninstall lottie-ios
```

After that deleted all code in Android project which refers to Lottie, deleted code in js files which refers to Lottie, Clean, Rebuild the project, made npm cache clean. 

But still getting this error: 

> undefined is not an object (evaluating reactNative.UIManager.LottieAnimationView.Commands). Any ideas how is possible to get rid of that error?    

  
 
<img width="356" alt="screen shot 2018-03-23 at 16 42 14" src="https://user-images.githubusercontent.com/10096433/37842431-62c7349e-2ec2-11e8-801f-536550c84804.png">

**Comment by felixus95** [comment]
+1

**Comment by Luckygirlllll** [comment]
I was able to get rid of that error, doing such steps: 

I have installed Lottie again. after that: 

```
react-native unlink lottie-react-native
react-native unlink lottie-ios
react-native uninstall lottie-react-native 
react-native uninstall lottie-ios
```
After that restarted my laptop
