### ISSUE TITLE
my animation do not play !

### ISSUE THREAD

**Issue by ali226281** [react-community/lottie-react-native#308]
I make an animation in after effect and export json with bodymovin,but it does not play in my react native project, and only the last frame is shown!
 please help me.

[tabloo.zip](https://github.com/airbnb/lottie-react-native/files/1866227/tabloo.zip)

**Comment by herman-rogers** [comment]
So the first thing for this, have you tested another animation to make sure your RN setup is working (just as a precaution)?

That being said, I tested your animation in my project and it doesn't seem to play either - so this might be an issue with the way you've exported it from AE, can you double check to see if the animation plays there (I'll check as well)?

**Comment by ali226281** [comment]
Thank you for your answer. I tried with other files. And those files were played correctly. I will send you the .eap file.
 I active 3D layer in after effect and I think lottie-react-native do not support 3D layer.Is my guess right?
[tabloo-files.zip](https://github.com/airbnb/lottie-react-native/files/1870100/tabloo-files.zip)

**Comment by herman-rogers** [comment]
Yea that's correct, 3D layers are not supported.

**Comment by tomek29k** [comment]
Hello, are there any plans to support 3D layers at all?
