### ISSUE TITLE
Question: Is there a way to know when the animation is loaded?

### ISSUE THREAD

**Issue by gisellezeitoune** [react-community/lottie-react-native#316]
Is there a callback when an animation is loaded? I'm trying to play an animation but it hasn't loaded yet. Right now I have several `SetTimeout`s to make sure the animation is correctly loaded.
Also, is there  way to know when an animation has finished?

**Comment by emilioicai** [comment]
Unfortunately there is no `onFinished` method in React Native's Lottie API. You can use React Native's `Animated` API to control when the animation has ended as it is show in `LottieAnimatedExample.js`: 

https://github.com/airbnb/lottie-react-native/blob/b932a2af98c2dfe22484e8c0e22bbc2ab551e4c9/example/js/LottieAnimatedExample.js#L74
