### ISSUE TITLE
Android autoplay does not work

### ISSUE THREAD

**Issue by guitar9** [react-community/lottie-react-native#318]
Hi,

autoplay does not work in Android. The Animation is there but it does not play. Anybody knows why?

```
                    <Animation
                        ref={animation => {
                            this.animation = animation;
                        }}
                        style={{
                            width: 80,
                            height: 80
                        }}
                        autoPlay = {true}
                        loop={true}
                        source="duck_och.json"
                    />
```

**Comment by emilioicai** [comment]
Does it work if you call `this.animation.start()` in your `componentDidMount()` ?

**Comment by gvlekke** [comment]
For ios it also doesnt work. Only when you do `this.animation.start()` in componentDidMount.
Thats a little bit frustrating when the rendering of the component is not there in the initial state.

**Comment by mnlbox** [comment]
@emilioicai @gpeal @Minishlink @lelandrichardson

**Comment by Minishlink** [comment]
Hello @mnlbox, can you try with the last version please? `2.5.8`
I did a fix for when the animation's view was not yet available when autoplay was executed.

**Comment by mnlbox** [comment]
@Minishlink I'm using version `2.3.2` so it's fix by package update?

**Comment by nicsachin** [comment]
does it work now

**Comment by emilioicai** [comment]
@nicsachin last version should be fine

**Comment by nicsachin** [comment]
I have react native version .55

**Comment by emilioicai** [comment]
then try `lottie-react-native` 2.5.11, it should be fine

**Comment by nicsachin** [comment]
I am using that only

**Comment by emilioicai** [comment]
you mean it's not working for you with version 2.5.11?

**Comment by nicsachin** [comment]
Yes
