### ISSUE TITLE
Version 2.5.0

### ISSUE THREAD

**Issue by GituBojan** [react-community/lottie-react-native#322]
Hi! 

Unfortunately I get following error while building for Android after the update from 2.3.2

> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v13/view/DragAndDropPermissionsCompat.class

Looking forward for your reply. 2.3.2 works perfectly fine.

Bojan

**Comment by emilioicai** [comment]
It looks like a resource conflict, please try fully cleaning you project and rebuilding. If that fails make sure you have the proper configurations on your `platforms/android/build.gradle`:

```
configurations {
    all*.exclude group: 'com.android.support', module: 'support-v13'
}
```
