### ISSUE TITLE
PNG not working in json

### ISSUE THREAD

**Issue by turooblanco** [react-community/lottie-react-native#325]
Hi

Im exporting a json file with after effects and the animated text seems to be ok, the issue I'm dealing with is the png file within the animation, is not showing on the json file, it just show a PNG file icon

How can i fix this?

**Comment by turooblanco** [comment]
That's exactly what I've been doing and doesn't seems to work

**Comment by rodrigoelp** [comment]
Hi @turooblanco, you need to set the assets folder as part of the lottie view, as you can read it [here](https://github.com/react-community/lottie-react-native/blob/master/docs/api.md#component-api) under the section `imageAssetsFolder`

Do notice, it indicates **iOS** will ignore this property (I do not know if that means the image is not going to load at all). The recommendation I've read from the community is that is always best to render all the content as vector graphics, which is pretty easy to deal with when most of your content has been designed in Illustrator (drag the illustrator file in AE, then create shape layers as described [here](https://helpx.adobe.com/after-effects/atv/cs6-tutorials/converting-imported-vector-graphics-from-illustrator-to-shape-la.html)

**Comment by joaohenriquef** [comment]
Where should this folder be? Is the `imageAssetsFolder` a relative path from the .js file instantiating `LottieView` or is it an absolute path? If the latter, which folder should I consider root? `android/`?

**Comment by joaohenriquef** [comment]
Thanks for the quick reply! Minutes after posting the question I found the answer in the docs, my bad ;). 

Adding to your answer, if somebody finds this having the same problem, remember to run `react-native run-android` every time you update the assets.
