### ISSUE TITLE
Animation never hides when it finish

### ISSUE THREAD

**Issue by Jeanluis019** [react-community/lottie-react-native#329]
I'm playing an animation, but when it has finished it keeps static on the screen. How can I hide or remove the animation when it has finished?

For now I have only tested on Android 6.0.

**Comment by Jeanluis019** [comment]
Typo error

**Comment by rodrigoelp** [comment]
Hi @Jeanluis019, one way to **know** your animation has finished is to control the animation yourself via an `Animated.Value` object assigned to `progress`.

That way, you will be able to play the animation via `Animated.timing().start(() => { /* callback to indicate it has finished */ })`

An example (written here, so might not be valid) is:

```tsx
class SomeComponent extends React.PureComponent {
    animationProgress = Animated.Value(0);
    state = { isAnimationVisible: true };

    componentDidMount() {
        Animated.timing(this.animationProgress, { toValue: 1, duration: 2000 })
            .start(() => this.setState(s => ({ ...s, isAnimationVisible: false }));
    }

    render() {
        if (this.state.isAnimationVisible) {
          const interpolation = this.animationProgress.interpolate({ inputRange: [0, 1], outputRange: [0, 0] });
          return (
             <View>
                  <LottieView source={require("./someAnimation.json")} progress={interpolation} />
             </View>
          );
        }
        return <View />;
    }
}
```

As far as I know, lottie does not provide a callback or mechanism to control the animation and give you feedback of its progress.
