### ISSUE TITLE
in android 4.2 Crash

### ISSUE THREAD

**Issue by liliangzdh** [react-community/lottie-react-native#331]
<img width="927" alt="d37484a9-76bc-4c89-8072-a6892d566313" src="https://user-images.githubusercontent.com/16744633/40035543-d3045b9c-5834-11e8-924f-7487840dbceb.png">
<img width="1336" alt="16b8c43a-8112-4f8e-ab53-5311fddd2b0e" src="https://user-images.githubusercontent.com/16744633/40035544-d4201f48-5834-11e8-921e-64359d6127aa.png">

**Comment by liliangzdh** [comment]
I has import support V4 and V7。
<img width="737" alt="f1aa8317-fd3c-476f-8740-c1da1d5eba46" src="https://user-images.githubusercontent.com/16744633/40035636-2e02358c-5835-11e8-8683-42c72a2e5ed9.png">

**Comment by liliangzdh** [comment]
@adrianleb can you help us

**Comment by manuhook** [comment]
Same as https://github.com/airbnb/lottie-react-native/issues/321

**Comment by yk3372** [comment]
this maybe help you #351
