### ISSUE TITLE
npm archive contains Android build artifacts

### ISSUE THREAD

**Issue by koenpunt** [react-community/lottie-react-native#336]
As can be seen in this image, the npm archive contains build artifacts:

![image](https://user-images.githubusercontent.com/351038/40974922-7e500326-68c9-11e8-9021-b7d1d66fb38a.png)

A direct link to the archive: https://registry.npmjs.org/lottie-react-native/-/lottie-react-native-2.5.0.tgz

**Comment by emilioicai** [comment]
Thanks for pointing this out. This should be fixed in 2.5.6
