### ISSUE TITLE
No git tag exists for version v2.5.0

### ISSUE THREAD

**Issue by koenpunt** [react-community/lottie-react-native#337]
As can be seen on this page; https://github.com/airbnb/lottie-react-native/tags, there's no tag available for v2.5.0. 

This causes an issue with me not being able to use this library using CocoaPods (I have a similar setup as Artsy has for https://github.com/artsy/emission/)

**Comment by bondparkerbond** [comment]
This may or may not be related, but in the documentation for Getting Started with Lottie in React Native(http://airbnb.io/lottie/react-native/react-native.html) the version specified to install is v2.3.2 and not v2.5.0. Could we update the documentation to either use the latest supported version or add an explanation that 2.3.2 is the preferred version/why we aren't using v2.5.0 in the set up explanations?

**Comment by emilioicai** [comment]
sorry for that, I just pushed the missing tags
