### ISSUE TITLE
Android fails to compile - Dex cannot parse version 52 byte code.

### ISSUE THREAD

**Issue by JesperLekland** [react-community/lottie-react-native#345]
Since the release of lottie-android@2.5.6 the java library requires java 1.8 to compile, something I couldn't get to work nicely (at all) with react-native. 

The error is 
```
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
```
and can be attributed to [this line](https://github.com/airbnb/lottie-react-native/blob/4322a8af3cb2f117d9709a0235a550dee7d3de17/src/android/build.gradle#L26) in the build.gradle. 

One easy fix is to simply skip the wildcard in `2.5.+` in favor of `2.5.5` or any version below.

**Comment by ionut-movila** [comment]
For those using Lottie in react native, the best option at the moment is described here: https://github.com/airbnb/lottie-android/issues/822#issuecomment-401776909

**Comment by wynch** [comment]
I just lost 1 day to debug that, thanks for the quick fix ! Maybe the build.gradle from `Lottie-react-native` should specify a more precise android dependency ?

**Comment by PerspectivesLab** [comment]
what i would recommend as a perm fix for you and if your are using a previous version of gradle  ( has many other libs will target java 8 as well, and the problem will be recurrent, and we also want to use the latest lottie features for 2.5.+ ):

1/ set min gradle version if its not the case in android studio:
```
buildscript {
    repositories {
		 
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
    }
}
```
2/ switch jdk to JAVA 8 in android studio -> File -> project structure

3/ in your main gradle file add support for java 8:
```
android {
....
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
.....

```

be aware : i think java 8 support on android is min api 24... so this will limit compatibility for previous android versions ?

**Comment by JesperLekland** [comment]
@PerspectivesLab I tried the above but even the gradle sync refused to work then. I'm not sure how react-native is affected by gradle version

**Comment by PerspectivesLab** [comment]
@JesperLekland be sure to upgrade to the latest version of android studio :  as today 3.1.3
clean your project, then close android studio, then delete folders "build" in your project, and open back android studio

**Comment by emilioicai** [comment]
It looks like lottie-android is going to be reverting the java 8 update (https://github.com/airbnb/lottie-android/issues/822#issuecomment-403194265) so this won't be an issue soon

**Comment by JJMoon** [comment]
I fixed the issues by changing other google dependent issues.

I guess the problem was in the combination of google versions, not Lottie.

**Comment by Christopotamus** [comment]
@JJMoon Any hints as to what you did? I'm getting the same error as you.

**Comment by Christopotamus** [comment]
This did the trick for me. 
I put this in android/app/build.gradle 
```
compile (project(':lottie-react-native')) {
     exclude group: 'com.android.support'
}
```
