### ISSUE TITLE
Couldn't remove the lottie package in android

### ISSUE THREAD

**Issue by MohanadeviK** [react-community/lottie-react-native#348]
Suddenly my app not working in android. Particularly release build I have got this error https://github.com/react-community/lottie-react-native/issues/277. So, I tried to remove lottie package but got another error *Undefined is not an object (evaluating 'i.UIManager.LottieAnimationView.Commands')*. 

After removing my lottie package in my app in index.android.bundle still has some lottie reference code. Any solution for this?

**Comment by anuraginwadi** [comment]
Refer to https://github.com/react-community/lottie-react-native/issues/303
