### ISSUE TITLE
Animations flicker or won't show after update (Android only, iOS works perfectly)

### ISSUE THREAD

**Issue by ant-fx** [react-community/lottie-react-native#362]
Hi Guys,

Thanks for such a great library!

### Description

After updating to Lottie Android to `2.5.5` and lottie-react-native to `2.5.6` I've started getting the following warnings and my animations are blank. This was working 100% previously with the same animations and same code.

Any anyone suggest why these warnings might have started appearing even though I'm setting calling `enableMergePathsForKitKatAndAbove(true)`? 

---

    W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
    W/LOTTIE: Animation contains merge paths. Merge paths are only supported on KitKat+ and must be manually enabled by calling enableMergePathsForKitKatAndAbove().
    W/LOTTIE: Animation contains merge paths but they are disabled.

---

    <Animation
      style={styles.layer1}
      source={PlanetAnimation}
      progress={this.state.progress1}
      enableMergePathsAndroidForKitKatAndAbove
    />

---

I have tried adding the `enableMergePathsAndroidForKitKatAndAbove` flag on the `Animation` element but that does not help.

I have also tried modifying the the `LottieAnimationViewManager` to force `view.enableMergePathsForKitKatAndAbove(true)` but I still get the same warning and my animations wont' display.

### Environemnt

`lottie-react-native@2.5.6`

`com.airbnb.android:lottie:2.5.5`

**Comment by ant-fx** [comment]
Update: This only seems to effect `>=2.5.1`, `2.5.0` works perfectly

**Comment by sujitpk-perennial** [comment]
+1 Facing issue after upgrading to 2.5.6

**Comment by sujitpk-perennial** [comment]
+1 Facing issue after upgrading to 2.5.6

**Comment by jdnichollsc** [comment]
I can't see my animations (an empty square) with the last version:
`"lottie-react-native": "^2.5.6"`
Regards, Nicholls

**Comment by Rikkiabb** [comment]
+1 on this, facing the same issue after upgrading to 2.5.6. Works fine on iOS, flickers on droid.

**Comment by Sammekl** [comment]
Exact same issue here, works fine on iOS, flickers and won't animate on Android

**Comment by Taylor123** [comment]
Seeing the same issue. Has anyone found the root cause or workaround for this?

**Comment by sujitpk-perennial** [comment]
I will suggest not to use 2.5.6 version. Switch to 2.5.0

**Comment by emilioicai** [comment]
I just published 2.5.7 including a fix for the play method on Android, can you guys check with the latest version?
