### ISSUE TITLE
Failed prop type: undefined is not an object (evaluating 'Object.keys(flattened)')

### ISSUE THREAD

**Issue by Jakst** [react-community/lottie-react-native#364]
### Description

The following warning is thrown when displaying animations that don't have a style object.

```
Failed prop type: undefined is not an object (evaluating 'Object.keys(flattened)')
```

### Steps to Reproduce

1. Create a LottieView without a style-property, i.e.

```typescript
export class Animation extends React.Component {
    animation

    componentDidMount() {
        this.animation.play()
    }

    render() {
        return <LottieView ref={animation => (this.animation = animation)} source={require('./animation.json')} />
    }
}
```

2. Observe the animation through your app

**Expected behavior:** Animation plays without warnings.

**Actual behavior:** The above warning is thrown.

### Versions

Introduced in 2.5.1 and still exists in 2.5.6. Both iOS and Android.

**Comment by emilioicai** [comment]
Fixed on master:
https://github.com/react-community/lottie-react-native/commit/ec60a087ccd819fc7901d8d8355407f5b1f6c543

The next release (2.5.10) will include this fix

**Comment by nickarora** [comment]
@emilioicai when can we expect 2.5.10?
