### ISSUE TITLE
Removing an view while the animation is running incorrectly warns

### ISSUE THREAD

**Issue by esprehn** [react-community/lottie-react-native#365]
### Description

Removing the view that has a currently running animation will show a yellow warning box with:

"Trying to animate a view on an unmounted component".

For example our loading spinner always warns because it's animating when we navigate to the main part of the app.

### Steps to Reproduce

1. Add a `<LottieView source='example.json' autoPlay />`
2. Navigate away or render that component again so that the LottieView is replaced.

**Expected behavior:** Should not warn.

**Actual behavior:** Warns always when switching views.

### Versions

2.5.6

(We upgraded from 2.3.2 where it used to not warn about this.)

**Comment by isaaclem** [comment]
When you trying to navigate away from that component, set LottieView autoPlay to false.

```<LottieView source='example.json' autoPlay={toStop} />```

**Comment by ex3ndr** [comment]
Actually there are some other problems with lottie on android and react doesn't stop animation after unmount (you can check it via profiling). You can just wrap everything in your component and stop animation via ref.

**Comment by frankfaustino** [comment]
I've tried setting ref to the `LottieView` and using `this.ref.reset()` to stop the animation. I've also tried `autoPlay={false}` upon component unmount. Neither of these work are working and the YellowBox warning `"Trying to animate a view on an unmounted component"` persists. Halp!

**Comment by 1pocketaces1** [comment]
same problem here

**Comment by NetPumi2** [comment]
+1

**Comment by ImadeLak** [comment]
+1

**Comment by emilioicai** [comment]
I guess we can just remove the warning as it's not providing much value here. I will include this in the next release

**Comment by rodrigoelp** [comment]
So, the suggestion is to implement ourselves the `autoPlay` functionality?

I had a workaround to this (which wasn't that different to this code) but it is a true shame the api does not seem to be working as expected.

**Comment by emilioicai** [comment]
fixed on 2.5.9
