### ISSUE TITLE
Lottie doesn't work on iOS

### ISSUE THREAD

**Issue by jdnichollsc** [react-community/lottie-react-native#368]
### Description

I can't see the animation with the version **0.56.0** of *React Native*, only a blank screen

### Steps to Reproduce

```
render() {
  return (
    <View style={Style.container}>
        <LottieView
          source={require('./animation.json')}
          autoPlay={true}
          loop={true}
          style={{ backgroundColor: 'white', width: 200, height: 200 }}
        />
    </View>
  )
}
```

**Expected behavior:** Execute the animation and show something

**Actual behavior:** Empty screen
<img width="559" alt="screenshot" src="https://user-images.githubusercontent.com/2154886/44290495-92d67380-a23e-11e8-8d0f-877ff33116a4.png">

### Versions

You can get this information from executing `npm version`.
```
{ MyApp: '1.0.0',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  cldr: '31.0.1',
  http_parser: '2.7.0',
  icu: '59.1',
  modules: '57',
  nghttp2: '1.25.0',
  node: '8.9.4',
  openssl: '1.0.2n',
  tz: '2017b',
  unicode: '9.0',
  uv: '1.15.0',
  v8: '6.1.534.50',
  zlib: '1.2.11' }
```

**Comment by emilioicai** [comment]
did you try with other animations? also, did you try to clean up your iOS project and build again?

**Comment by jdnichollsc** [comment]
@emilioicai Works after add the libraries manually from Xcode
