### ISSUE TITLE
error: package com.airbnb.android.react.lottie does not exist

### ISSUE THREAD

**Issue by huurray** [react-community/lottie-react-native#380]
hello i found it difficult to use lottie-react-native.
and i hope anyone help me.

i installed lottie and i linked it.
and when i run 'react-native run-android'
i got this error..

> Task :app:compileDebugJavaWithJavac FAILED
C:\Users\JUNHYEOK HEO\dev\react-native-firebase-starter-kit\android\app\src\main\java\com\midnightplan\rnfirebasestarterkit\MainApplication.java:7: error: package com.airbnb.android.react.lottie does not exist
import com.airbnb.android.react.lottie.LottiePackage;
                                      ^
C:\Users\JUNHYEOK HEO\dev\react-native-firebase-starter-kit\android\app\src\main\java\com\midnightplan\rnfirebasestarterkit\MainApplication.java:48: error: cannot find symbol
            new LottiePackage(),
                ^
  symbol: class LottiePackage
2 errors

### Versions

    "fbjs": "^0.8.17",
    "lottie-react-native": "^2.5.8",
    "react": "^16.3.2",
    "react-native": "^0.55.3",
    "react-native-firebase": "^4.3.6"

**Comment by huurray** [comment]
i got this. it missed 'compile' in app/build.gradle

![image](https://user-images.githubusercontent.com/41982439/45334561-3c96ef00-b5b6-11e8-8584-13b97af27633.png)

**Comment by devpascoe** [comment]
> i got this. it missed 'compile' in app/build.gradle
> 
> ![image](https://user-images.githubusercontent.com/41982439/45334561-3c96ef00-b5b6-11e8-8584-13b97af27633.png)

Hi there.
What might be the modern equivalent of this in 2020? "implementation" or "api" since compile is deprecated.

**Comment by aemc** [comment]
@devpascoe I think it's implementation
