### ISSUE TITLE
Need to use new dependency configurations in build.gradle!

### ISSUE THREAD

**Issue by kevinmeresse** [react-community/lottie-react-native#383]
In src/android/build.gradle, 'provided' and 'compile' are deprecated and will be removed at the end of 2018.
I know there was a PR addressing this issue (https://github.com/react-community/lottie-react-native/pull/354) and it has been approved and merged to master, but for some reason I'm not seeing it in the latest version. Has it been mistakenly removed while resolving conflicts?

**Comment by emilioicai** [comment]
this should be fixed on 2.5.9
