### ISSUE TITLE
After Effects animations are rendered with black areas on iOS. Works fine in LottieFiles

### ISSUE THREAD

**Issue by oriharel** [react-community/lottie-react-native#397]
### Description

an animation, created with After Effects, that works fine in LottieFiles.com, shows up with black areas when using inside a React Native app on iOS.

Here's how it looks in LottieFiles.com:

<img width="186" alt="goodlottie" src="https://user-images.githubusercontent.com/367269/47137425-2c61e600-d2bf-11e8-8d17-3ba2fcec338d.png">

And here's how it looks inside the RN app:

<img width="414" alt="badlottie" src="https://user-images.githubusercontent.com/367269/47137442-3552b780-d2bf-11e8-8461-e881bd4365e2.png">

Here's the JSON file:

[123steps_03.json.zip](https://github.com/react-community/lottie-react-native/files/2490645/123steps_03.json.zip)

**Expected behavior:** [What you expected to happen]
The animation should render fine, like in LottieFiles

**Actual behavior:** [What actually happened]
There are black areas (seems like the "fill" property of the arc) that shouldn't be there

### Versions

"lottie-react-native": "^2.5.6",
"react-native": "0.54.2"

**Comment by Dihan101** [comment]
Yes! It's the fill's fault. I think you need to fix it directly on the AE.

**Comment by rodrigoelp** [comment]
Hi, just contributing a bit more on this... @Dihan101 is right, check your ae file and find the path. Check ae is not setting the colour of the fill to black and in some cases, you can even remove it.

Unfortunately, the differences between the native and web code can be quite annoying.

**Comment by oriharel** [comment]
Yes - after we fixed the after effect it was ok.
