### ISSUE TITLE
Sample app does not have render graph or any other profiling options

### ISSUE THREAD

**Issue by lbenedetto** [react-community/lottie-react-native#403]
### Description
According to the [documentation](https://airbnb.io/lottie/android/performance.html), I should be able to access a render graph. 

However, after building the example app to my phone as per [the instructions here](https://airbnb.io/lottie/react-native/sample-app.html), there are no such options. In fact, nowhere in the entire repo does the String "Render Graph" appear.

I just get a screen like this where I can play various Lottie animations
https://i.imgur.com/0fldcUI.png

**Comment by emilioicai** [comment]
Yup, you're right, that's an old piece of documentation so I will remove it.

**Comment by lbenedetto** [comment]
Is there a different way to get frame render information?

**Comment by lbenedetto** [comment]
Oh, I didn't know there was a native sample app. I'm pretty sure this is the app linked in the documentation. Guess I wasted a lot of time setting up a react native environment for nothing.
