### ISSUE TITLE
Compilation error after linking lottie-ios

### ISSUE THREAD

**Issue by OcteauJeremy** [react-community/lottie-react-native#408]
### Description

I tried to link lottie-ios but I have a compilation error. 
Lottie works fine with the android emulator.

### Steps to Reproduce

1. npm i --save lottie-react-native@2.3.2
2. react-native link lottie-ios
3. react-native link lottie-react-native
4. After this, open the Xcode project configuration and add the Lottie.framework as Embedded Binaries

**Actual behavior:**
I have multiple compilation errors starting by this one:

```
/Users/user/Code/CSULB/CECS_543/anacodiam_ios/node_modules/lottie-react-native/src/ios/../../../react-native/ReactCommon/fabric/graphics/platform/ios/float.h:8:10: fatal error: "limits" file not found
#include <limits>
While building module "UIKit" imported from /Users/user/Code/CSULB/CECS_543/anacodiam_ios/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTViewManager.h:8:
While building module "Foundation" imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: fatal error: could not build module "CoreFoundation"
#include <CoreFoundation/CoreFoundation.h>
```

### Versions
```
{ anacodiam_ios: '0.0.1',
  npm: '6.4.1',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '67',
  napi: '3',
  nghttp2: '1.34.0',
  node: '11.1.0',
  openssl: '1.1.0i',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.23.2',
  v8: '7.0.276.32-node.7',
  zlib: '1.2.11' }
```

### Screenshots
Here is my project settings (File > Project Settings):
[https://imgur.com/MgyNqDj](https://imgur.com/MgyNqDj)

My general settings:
[https://imgur.com/HoghSUA](https://imgur.com/HoghSUA)

My Header Search paths:
[https://imgur.com/Hd5ngHh](https://imgur.com/Hd5ngHh)
I added `$(SRCROOT)/../node_modules/react-native/React/` as recommanded in this issue [https://github.com/react-community/lottie-react-native/issues/373](https://github.com/react-community/lottie-react-native/issues/373
)

And my build phases:
[https://imgur.com/cg630rS](https://imgur.com/cg630rS)

Thank you in advance.

**Comment by emilioicai** [comment]
I think this is an error with `lottie-ios` itself and not with `lottie-react-native`. Would you like to create an issue on their repo?
