### ISSUE TITLE
Lottie Clipping Ellipses in React-Native

### ISSUE THREAD

**Issue by sabbakeynejad** [react-community/lottie-react-native#413]
Lottie is Clipping Ellipses in React-Native, I have tried using it in the web (Lottie files) Here is a link to [the web version that works. ](https://lottiefiles.com/share/St6gkE)

As this is working online, I think it might be a React-Native problem?

And this is a [link to my JSON file ](https://api.myjson.com/bins/9orie)

Below shows how it is rending on my Ipad

![And this is how it appears on my Ipad](https://i.imgur.com/daTXYew.png)

**Comment by emilioicai** [comment]
It looks like this animation uses one of the After Effects features  lottie-android/lottie-ios doesn't support. Can you double check if you are using one? Here's the list of supported features:

https://airbnb.io/lottie/supported-features.html

**Comment by sabbakeynejad** [comment]
I solved the problem, I think I was using an outdated version of Bodymovin. I reinstalled [Bodymovin from this link](http://aescripts.com/bodymovin/) and it started working.
